### ISSUE TITLE
Sample doesn't run

### ISSUE THREAD

**Issue by ariasf** [playframework/play-socket.io#12]
I have been trying to add this to one of the projects I  am working on and i get bunch of errors following the README.MD so I decided to start from  0 and run the samples, i get this error trying to run the chat example 
@ `C:\source\play-socket.io> sbt scalaChat/run`

``` scala
[info] Headers created for 19 files:
[info]   C:\source\play-socket.io\src\main\scala\play\api\mvc\ByteStringBodyParser.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\DeserializedRequestHeader.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\EngineIO.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\EngineIOAkkaSerializer.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\EngineIOManagerActor.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\EngineIOSessionActor.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\EngineIOSessionHandler.scala
[info]   C:\source\play-socket.io\src\main\scala\play\engineio\protocol\EngineIOProtocol.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\SocketIOConfig.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\SocketIOEvent.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\SocketIOModule.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\SocketIOSessionFlow.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\javadsl\SocketIOSessionFlowHelper.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\protocol\SocketIOProtocol.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\scaladsl\SocketIO.scala
[info]   C:\source\play-socket.io\src\main\scala\play\socketio\scaladsl\SocketIOEventCodec.scala
[info]   C:\source\play-socket.io\src\main\java\play\socketio\SocketIOEventAck.java
[info]   C:\source\play-socket.io\src\main\java\play\socketio\javadsl\SocketIO.java
[info]   C:\source\play-socket.io\src\main\java\play\socketio\javadsl\SocketIOEventCodec.java
[info] Compiling 1 protobuf files to C:\source\play-socket.io\target\scala-2.12\src_managed\main
[info] Compiling schema C:\source\play-socket.io\src\main\protobuf\engineio.proto
protoc-jar: protoc version: 330, detected platform: windows 10/amd64

:\source\play-socket.io\target\scala-2.12\src_managed\main, -IC:\source\play-socket.io\src\main\protobuf, -IC:\source\play-socket.io\target\protobuf_external, C:\source\play-socket.io\src\main\protobuf\engineio.proto]
'python' is not recognized as an internal or external command,
operable program or batch file.
--scala_out: protoc-gen-scala: Plugin failed with status code 1.
java.lang.RuntimeException: protoc returned exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.scala:146)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.sbtprotoc$ProtocPlugin$$anonfun$$compileProto$1(ProtocPlugin.scala:177)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$7.apply(ProtocPlugin.scala:189)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$7.apply(ProtocPlugin.scala:188)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:195)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:171)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (root/compile:protocGenerate) protoc returned exit code: 1
[error] Total time: 7 s, completed Jun 30, 2018 6:17:21 PM

C:\source\play-socket.io>
```

Any help will be greatly appreciated.  thanks in advance.

**Comment by jroper** [comment]
You need python installed and on your `PATH`, this is necessary to run the protobuf compiler.
